
package skeletonlisp.LExp;


public enum LExpTypes {
    NILTYPE, LVALUETYPE,
    LATOMTYPE, LIDTYPE,
    LNUMBERTYPE, LINTTYPE,
    LDOUBLETYPE, LPAIRTYPE,
    LERRORTYPE, LSTRINGTYPE,
    LCONDTYPE, LAPPLICATIONTYPE,
    LAMBDATYPE, CONDCASETYPE    
}
